language: node_js
node_js:
- "10"
cache: 
directories:
- node_modules
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database transaction_runner_test_db;' -U postgres
script:
- npm run test
notifications:
  email: false